CC = gcc
CC = cc
CFLAGs =-g -Wall -Werror -pedantic -ansi --std=c99

# list of binaries
BIN =eg01 eg02 eg02a

all: $(BIN)

clean:
	/bin/rm -f a.out *.o *.a $(BIN)

eg01: eg01.c

eg02: eg02.c

eg02a: eg02a.c

