CC = gcc
CC = cc
CFLAGS=-g -Wall -Werror -pedantic -ansi --std=c99

# list of binaris
BIN= eg01 eg02 eg03 eg04

all: $(BIN)

clean:
	/bin/rm -f a.out *.o *.a $(BIN)

eg01: eg01.c

eg02: eg02.c

eg03: eg03.c

eg04: eg04.c
