CC=gcc
CFLAGS=-g -Wall

all: eg01 eg02 eg03 eg04 eg05 eg06 eg07

eg01: eg01.c

eg02: eg02.c

eg03: eg03.c

eg04: eg04.c

eg05: eg05.c

eg06: eg06.c

eg07: eg07.c

clean:
	/bin/rm -f a.out *.o eg01 eg02 eg03 eg04 eg05 eg06 eg07
