CC=gcc
CFLAGS=-g -Wall

all: ex02 ex03 ex04 ex05 ex06 ex07

ex02: ex02.c

ex03: ex03.c

ex04: ex04.c

ex05: ex05.c

ex06: ex06.c

ex07: ex07.c

clean:
		/bin/rm -f 	a.out *.o ex02 ex03 ex04 ex05 ex06 ex07
