all:
	cd c05 && make all && cd ..
	cd c06 && make all && cd ..
	cd c07 && make all && cd ..
	cd c08 && make all && cd ..
	cd c10 && make all && cd ..

clean:

	cd c05 && make clean && cd ..
	cd c06 && make clean && cd ..
	cd c07 && make clean && cd ..
	cd c08 && make clean && cd ..
	cd c10 && make clean && cd ..
