all:
	cd c04 && make all && cd ..
	cd c05 && make all && cd ..
	cd c06 && make all && cd ..
	cd c07 && make all && cd ..
	cd c08 && make all && cd ..
	cd c09 && make all && cd ..
	cd c10 && make all && cd ..
	cd c11 && make all && cd ..
	cd c13 && make all && cd ..
	cd c15 && make all && cd ..
	cd libcommon && make all && cd ..

clean:

	cd c04 && make clean && cd ..
	cd c05 && make clean && cd ..
	cd c06 && make clean && cd ..
	cd c07 && make clean && cd ..
	cd c08 && make clean && cd ..
	cd c09 && make clean && cd ..
	cd c10 && make clean && cd ..
	cd c11 && make clean && cd ..
	cd c13 && make clean && cd ..
	cd c15 && make clean && cd ..
	cd libcommon && make clean && cd ..
	/bin/rm -f o
