CC=gcc

all: ch8exercise2  ch8exercise3  ch8exercise4  ch8exercise5  ch8exercise6  ch8exercise7  ch8exercise8  ch8exercise9  ch8exercise10  ch8exercise11  ch8exercise12  ch8exercise13  
ch8exercise2: 	ch8exercise2.c

ch8exercise3: 	ch8exercise3.c

ch8exercise4: 	ch8exercise4.c

ch8exercise5: 	ch8exercise5.c

ch8exercise6: 	ch8exercise6.c

ch8exercise7: 	ch8exercise7.c

ch8exercise8: 	ch8exercise8.c

ch8exercise9: 	ch8exercise9.c

ch8exercise10: 	ch8exercise10.c

ch8exercise11: 	ch8exercise11.c

ch8exercise12: 	ch8exercise12.c

ch8exercise13: 	ch8exercise13.c

clean:
	/bin/rm -f a.out *.o ch8exercise2  ch8exercise3  ch8exercise4  ch8exercise5  ch8exercise6  ch8exercise7  ch8exercise8  ch8exercise9  ch8exercise10  ch8exercise11  ch8exercise12  ch8exercise13  
